name: Discord Notification
on:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Notification
      if: github.event.pull_request.merged == true
      uses: appleboy/discord-action@master
      with:
        INPUT_WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
        INPUT_WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
        message: 'A pull request has been merged.'
