name: Discord Notification
on:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Discord Notification
        if: github.event.pull_request.merged == true
        uses: Ilshidur/action-discord@2.1.0
        with:
          args: '**${{ github.actor }}** pushed [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) to **${{ github.ref_name }}**'
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
